name: design_system_lints
description: A collection of lints and code edits to enforce UI standards within a codebase. Built with Sidecar.
version: 0.1.1
repository: https://github.com/pattobrien/design_system_lints
homepage: https://github.com/pattobrien/design_system_lints
issue_tracker: https://github.com/pattobrien/design_system_lints/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  sidecar: ^0.1.1

dev_dependencies:
  # flutter and design_system_annotations needed for testing
  design_system_annotations: ^0.1.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  lints: ^2.0.0
  # sidecar_lints: ^0.1.0-dev.3
  test: ^1.16.0

sidecar:
  lints:
    - box_constraints
    - box_shadow
    - color
    - edge_insets
    - icon
    - radius
    - text_style
    - theme_data
